config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#new"



  get '/styleguide', to: 'styleguide#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :games
  get '/play_game/:id', to: 'games#show', as: 'play_game'
  get '/create_game', to: 'games#new'

  get '/create_game_user/:id', to: 'game_users#create', as: 'create_game_user'
  # post '/create_game_user', to: 'game_users#create'
  resources :users
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :game_users
  has_many :users, through: :game_users
  belongs_to :winner, class_name: 'User', optional: true, foreign_key: :winner_id
  validates :name, presence: true, uniqueness: true
  VALID_PLAYER_MAX = 10
  VALID_PLAYER_MIN = 2
  validates :player_count, presence: true, 
  comparison: { less_than_or_equal_to: VALID_PLAYER_MAX, greater_than_or_equal_to: VALID_PLAYER_MIN },
  numericality: { only_integer: true }

  serialize :go_fish, GoFish

  def remaining_players 
    player_count - users.length
  end

  def start!
    return false unless player_count == users.length
    
    players = game_users.map { |game_user| Player.new(user_id: game_user.user_id, name: User.find(game_user.user_id).name) }
    go_fish = GoFish.new(players: players)
    go_fish.start
    update(go_fish: go_fish, started_at: DateTime.current)
  end

  def current_player
    User.find_by(name: go_fish.current_player.name)
  end

  def play_round(rank, player_name)
    player = go_fish.find_player_by_name(player_name)
    go_fish.play_round(rank, player)
    check_game_over
    self.save
  end

  def check_game_over
    if go_fish.over?
      finished_at = DateTime.current
      winner_id = go_fish.game_winner.user_id
    end
  end


end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @game = Game.new 
  end

  def create
    @game = Game.new(game_params)
    if @game.save 
      @game.users << current_user
      redirect_to play_game_url(@game)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def show
    @game = Game.find(params[:id])
    if @game.started_at
      if @game.go_fish.over?
        @game.update(finished_at: DateTime.current, winner_id: @game. go_fish.game_winner.user_id)
      end
    end
  end

  def index
    @games = Game.paginate(page: params[:page])
  end

  def update
    game = Game.find(params[:id])
    game.play_round(params[:Ranks], params[:Players])
    if game.go_fish.over?
      game.users.each do |user|
        partial = ApplicationController.render(partial: "games/game_over", locals: {game: game, current_user: user})
        ActionCable.server.broadcast("game_#{game.id}_#{user.id}", partial)
      end
    else
      game.users.each do |user|
        partial = ApplicationController.render(partial: "games/games_show", locals: {game: game, current_user: user})
        ActionCable.server.broadcast("game_#{game.id}_#{user.id}", partial)
      end
    end

    redirect_to game
  end

  private

  def game_params
    params.require(:game).permit(:name, :player_count)
  end
end

app/views/games/_ask.html.slim
 = form_for(game, url: game_path(game), remote: true)
  .card--padded.flex
    - if current_user.name == go_fish.current_player.name
      .form__group
        label.form__label for='Ranks' Ranks
        select.form__dropdown name='Ranks'
          - go_fish.current_player.hand_ranks.each  do |rank|
            option = rank
      .form__group
        label.form__label for='Players' Players
        select.form__dropdown name='Players'
          - go_fish.all_player_names_but_current.each do |name|
            option = name
      .flex.justify-end
        button.btn-primary type='submit' Ask
  

      

app/views/games/_game.html.slim
.card--padded.flex.justify-between
  .flex
    = game.name
  .flex 
    = "#{game.users.count}/#{game.player_count}"
  .flex
    = link_to 'Join Game', create_game_user_path(game), class: 'btn-primary'

app/views/games/_game_log.html.slim
.card
  .card__body
    - if  game.go_fish.history.empty?
      - if current_user.name == game.go_fish.current_player.name      
          p It's Your turn select a card!
      - else 
          p It is #{game.go_fish.current_player.name}'s turn
    -else
      - if current_user.name == game.go_fish.history.last.current_player_name
        - game.go_fish.history.last.current_player_message.each do |message|
          p = message
      - else 
        - game.go_fish.history.last.target_player_message.each do |message|
          p = message

app/views/games/_game_over.html.slim
= "#{game.go_fish.game_winner.name} won"

app/views/games/_games_show.html.slim
- if !game.started_at
  = "Waiting for #{game.remaining_players} #{game.remaining_players == 1 ? 'player' : 'players'}..."
- else 
  = "#{current_user.name}" 
  = render partial: 'games/play_game', locals: { game: game, current_user: current_user}

app/views/games/_hand.html.slim
.player-hand.flex-wrap
  .card__header 
    h2 Hand
  .card__body.flex.flex-wrap.gap-sm
    - go_fish.players.select { |player| player.user_id == current_user.id }[0].hand.map do |card|
      = image_tag "#{(card.suit).downcase}_#{card.rank.downcase}.svg", class: 'deck-card'

app/views/games/_play_game.html.slim
-if !game.go_fish.over?
  .flex.one-third-width 
    = render partial: 'games/hand', locals: { game: game, current_user: current_user, go_fish: game.go_fish }
    / = render 'games/players'
  .flex.flex-col.justify-around.three-quarters-width 
    = render partial: 'games/ask', locals: {game: game, current_user: current_user, go_fish: game.go_fish }
    = render partial: 'games/game_log', locals: {game: game, current_user: current_user, go_fish: game.go_fish }
-else
  = render partial: 'games/game_over', locals: {game: game, current_user: current_user, go_fish: game.go_fish }

app/views/games/_players.html.slim
.card--padded.flex.flex-wrap
  .card__header 
    h2 Players 
  .card__body  
    - if current_user.name == game.current_player.name
          - game.go_fish.players.map do |player| 
            li = player.name
    - else
      ul 
        - game.go_fish.players.map do |player| 
          li = player.name

app/views/games/index.html.slim
-provide(:title, 'index')

= link_to 'Create Game', create_game_path, class: 'btn--outline'
= render @games

app/views/games/new.html.slim
-provide(:title, 'Create')

= simple_form_for(@game) do |f|
  .card--padded
    .card__header 
      h1 Create Game  
    .card__body 
      = f.input :player_count
      = f.input :name
    .card__footer 
      .flex.flex_end 
        = f.submit "Create", class: "btn-primary"

app/views/games/show.html.slim
-provide(:title, 'Play Game')
.container.game-screen.gap-md data-controller="game" data-game-id=@game.id data-game-user_id=current_user.id
  .flex.gap-md data-game-target="game_page"
    = render partial: 'games/games_show', locals: { game: @game, current_user: current_user } 

  