config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#new"



  get '/styleguide', to: 'styleguide#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :games
  get '/play_game/:id', to: 'games#show', as: 'play_game'
  get '/create_game', to: 'games#new'

  get '/create_game_user/:id', to: 'game_users#create', as: 'create_game_user'
  # post '/create_game_user', to: 'game_users#create'
  resources :users
end

app/views/layouts/_header.html.slim
header.nav-bar
  = link_to 'GoFish', root_path, id: "logo", class: 'nav-bar__brand'
    
  .flex
    = link_to "Home", games_path, class: 'nav-bar__link'
    = link_to "Help", '#', class: 'nav-bar__link'
    - if logged_in? 
      / = link_to "Users", '#', class: 'nav-bar__link'
      = link_to "Log Out", logout_path, class: 'nav-bar__link', method: :delete

      / .form-group 
        label.form-label Account
        select.form-dropdown
          option 
          option 
            = link_to "Profile", current_user 
          option
            = link_to "Settings", '#' 
           
    / - else
      = link_to "Log in", login_path, class: 'nav-bar__link'

app/views/layouts/_rails_default.html.slim
  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_pack_tag 'stylesheets', 'data-turbolinks-track': 'reload'
  = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/application.html.slim
doctype html
html 
  head
    title
      = full_title(yield(:title))
    meta name="viewport" content="width=device-width,initial-scale=1"
    meta charset="utf-8"
    = render 'layouts/rails_default'
  body
    = render 'shared/flash'
    = render 'layouts/header'
    .container
      = yield